# Site settings
title: Shiral Wang
email: shiralwz@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  互联网程序员
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://iwangzheng.com" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username: shiralwz

# Build settings
markdown: kramdown
